name: Data
on:
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  snake:
    runs-on: ubuntu-lates
    steps:
      - uses: Platane/snk@v2
        with:
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
