name: Data
on:
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  snake:
    runs-on: ubuntu-lates
    steps:
      - uses: Platane/snk/svg-only@v2
        with:
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
